# Generated by Django 5.1.4 on 2024-12-31 20:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_project_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimation_number',
            field=models.CharField(default='EST-000', max_length=20, unique=True, verbose_name='Estimation #'),
        ),
    ]
