# Generated by Django 5.1.4 on 2024-12-31 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facility_material_productionprocess_personnel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['project__project_number', 'name'], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='productionlog',
            options={'ordering': ['-production_date'], 'verbose_name': 'Production Log', 'verbose_name_plural': 'Production Logs'},
        ),
        migrations.RemoveField(
            model_name='productionlog',
            name='project_number',
        ),
        migrations.AddField(
            model_name='productionlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='core.project'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='produced_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(db_index=True, help_text='Project number (e.g., 1001)', max_length=10, unique=True, verbose_name='Project #'),
        ),
    ]
