# Generated by Django 5.1.4 on 2024-12-31 20:22

from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241231_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='structure_type',
            field=models.CharField(default='INDUSTRIAL', max_length=50, choices=[
                ('INDUSTRIAL', 'Industrial Building'),
                ('COMMERCIAL', 'Commercial Building'),
                ('RESIDENTIAL', 'Residential Building'),
                ('WAREHOUSE', 'Warehouse'),
                ('OTHER', 'Other'),
            ], verbose_name='Structure Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_structures',
            field=models.IntegerField(default=1, verbose_name='No. of structures'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_2_ack',
            field=models.BooleanField(default=False, verbose_name='Payment 2 Ack'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_3_ack',
            field=models.BooleanField(default=False, verbose_name='Payment 3 Ack'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment 4'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_4_ack',
            field=models.BooleanField(default=False, verbose_name='Payment 4 Ack'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment 5'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_5_ack',
            field=models.BooleanField(default=False, verbose_name='Payment 5 Ack'),
        ),
        migrations.AddField(
            model_name='project',
            name='preliminary_retention',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preliminary Retention'),
        ),
        migrations.AddField(
            model_name='project',
            name='ho_retention',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H.O Retention'),
        ),
        migrations.AddField(
            model_name='project',
            name='incoterm',
            field=models.CharField(default='EXW', max_length=20, choices=[
                ('EXW', 'Ex Works'),
                ('FOB', 'Free on Board'),
                ('CIF', 'Cost, Insurance, and Freight'),
                ('DDP', 'Delivered Duty Paid'),
            ], verbose_name='Incoterm'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_of_work',
            field=models.TextField(default='', verbose_name='Scope of Work'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_nature',
            field=models.CharField(default='NEW', max_length=20, choices=[
                ('NEW', 'New Construction'),
                ('EXPANSION', 'Expansion'),
                ('RENOVATION', 'Renovation'),
                ('MAINTENANCE', 'Maintenance'),
            ], verbose_name='Project Nature'),
        ),
        migrations.AddField(
            model_name='project',
            name='galvanized',
            field=models.BooleanField(default=False, verbose_name='Galvanized'),
        ),
        migrations.AddField(
            model_name='project',
            name='galvanization_microns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Galvanization Microns'),
        ),
        migrations.AddField(
            model_name='project',
            name='m2_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='m2/Ton'),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_coat_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paint Coat 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_coat_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paint Coat 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_coat_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paint Coat 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='paint_coat_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paint Coat 4'),
        ),
        migrations.AddField(
            model_name='project',
            name='top_coat_ral_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Top Coat RAL Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='welding_process',
            field=models.CharField(default='SMAW', max_length=20, choices=[
                ('SMAW', 'Shielded Metal Arc Welding'),
                ('GMAW', 'Gas Metal Arc Welding'),
                ('FCAW', 'Flux Cored Arc Welding'),
                ('SAW', 'Submerged Arc Welding'),
            ], verbose_name='Welding Process'),
        ),
        migrations.AddField(
            model_name='project',
            name='welding_wire_aws_class',
            field=models.CharField(default='', max_length=50, verbose_name='Welding Wire AWS Class'),
        ),
        migrations.AddField(
            model_name='project',
            name='pqr_no',
            field=models.CharField(default='', max_length=50, verbose_name='PQR NO'),
        ),
        migrations.AddField(
            model_name='project',
            name='wps_no',
            field=models.CharField(default='', max_length=50, verbose_name='WPS NO'),
        ),
        migrations.AddField(
            model_name='project',
            name='standard_code',
            field=models.CharField(default='', max_length=50, verbose_name='Standard Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='down_payment_ack',
            field=models.BooleanField(default=False, verbose_name='Down Payment Ack'),
        ),
    ]
