# Generated by Django 5.1.4 on 2024-12-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241231_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planned_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planned_start_date',
        ),
        migrations.AddField(
            model_name='building',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Start Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Start Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progress (%)'),
        ),
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20, verbose_name='Status'),
        ),
    ]
