# Generated by Django 5.1.4 on 2024-12-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_project_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='design_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Design End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='design_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Design Start Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='qc_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='QC Inspection Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='qc_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='QC Remarks'),
        ),
        migrations.AddField(
            model_name='building',
            name='qc_status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Pass')], default='pending', max_length=20, verbose_name='QC Status'),
        ),
        migrations.AddField(
            model_name='building',
            name='shop_drawing_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shop Drawing End Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='shop_drawing_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shop Drawing Start Date'),
        ),
        migrations.AlterField(
            model_name='building',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Production End'),
        ),
        migrations.AlterField(
            model_name='building',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Production Start'),
        ),
        migrations.AlterField(
            model_name='building',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production End Date'),
        ),
        migrations.AlterField(
            model_name='building',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Production Start Date'),
        ),
    ]
