# Generated by Django 5.1.4 on 2024-12-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_building_design_end_date_building_design_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawdata', to='core.building'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawdata', to='core.project'),
        ),
    ]
