# Generated by Django 5.1.4 on 2025-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rawdata_building_alter_rawdata_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(db_index=True, help_text='Project number (e.g., PRJ-2024-001)', max_length=50, unique=True, verbose_name='Project #'),
        ),
    ]
