# Generated by Django 5.1.4 on 2025-01-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_building_area_building_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='project_number',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
    ]
