# Generated by Django 5.1.4 on 2025-01-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productionlog_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='project_number',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
    ]
