# Generated by Django 5.1.4 on 2025-01-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rawdata_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='part_type',
            field=models.CharField(choices=[('assembly', 'Assembly Part'), ('single', 'Single Part')], default='single', help_text='Indicates whether this is an assembly part or a single part', max_length=20, verbose_name='Part Type'),
        ),
    ]
