# Generated by Django 5.1.4 on 2025-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rawdata_part_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='part_type',
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='part_designation',
            field=models.CharField(help_text="Part designation (e.g., 'ASSEMBLY-BEAM-001' or 'SINGLE-PLATE-001')", max_length=255, verbose_name='Part Designation'),
        ),
    ]
