# Generated by Django 5.1.4 on 2025-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_rawdata_part_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='row_id',
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Row ID'),
        ),
    ]
