# Generated by Django 5.1.4 on 2025-01-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_row_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='name',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='name_designation',
            field=models.CharField(blank=True, help_text='Structural element type (e.g., Beam, Column, Bracing, Joist, Plate, etc.)', max_length=255, verbose_name='Name Designation'),
        ),
    ]
