# Generated by Django 5.1.4 on 2025-01-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_name_to_name_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='core.building'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='building_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(db_index=True, help_text='Project number', max_length=50, unique=True, verbose_name='Project #'),
        ),
    ]
