# Generated by Django 5.1.4 on 2025-01-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_productionlog_building_productionlog_building_name_and_more'),
    ]

    operations = [
    ]
